<?php
namespace Jankx\Extensions\TourJourney\Admin;

use Jankx\Extensions\TourJourney\PostTypes\JourneyPostType;

class JourneyBuilderMetabox
{
    const METABOX_ID = 'jankx_journey_builder';
    const META_KEY = '_jankx_journey_itinerary';

    public function register(): void
    {
        add_action('add_meta_boxes', [$this, 'addMetabox']);
        add_action('save_post', [$this, 'saveMetabox']);
        add_action('admin_enqueue_scripts', [$this, 'enqueueScripts']);
    }

    public function addMetabox(): void
    {
        add_meta_box(
            self::METABOX_ID,
            __('Itinerary Builder (Hành trình chi tiết)', 'jankx'),
            [$this, 'renderMetabox'],
            JourneyPostType::POST_TYPE,
            'normal',
            'high'
        );
    }

    public function renderMetabox($post): void
    {
        // Add nonce
        wp_nonce_field('jankx_save_journey_itinerary', 'jankx_journey_nonce');

        $itinerary = get_post_meta($post->ID, self::META_KEY, true);
        if (!is_array($itinerary)) {
            $itinerary = [];
        }

        // We will pass the saved itinerary to JS
        ?>
        <div id="jankx-journey-builder-app" class="jankx-journey-builder">
            <div class="journey-builder-desc">
                <p><em>Hãy chọn các <strong>Điểm đến</strong> ở cột bên phải, sau đó các điểm đến sẽ hiển thị ở đây để bạn kéo
                        thả sắp xếp và thêm thông tin thời gian (như: Ngày 1, Đêm 1...).</em></p>
            </div>

            <div id="journey-builder-list" class="journey-items-list">
                <!-- Generated by JS -->
            </div>

            <input type="hidden" id="jankx-journey-data" name="<?php echo esc_attr(self::META_KEY); ?>"
                value="<?php echo esc_attr(json_encode($itinerary)); ?>" />
        </div>

        <script>
            window.jankxSavedJourneyItinerary = <?php echo json_encode($itinerary); ?>;
        </script>
        <?php
    }

    public function saveMetabox(int $post_id): void
    {
        if (!isset($_POST['jankx_journey_nonce']) || !wp_verify_nonce($_POST['jankx_journey_nonce'], 'jankx_save_journey_itinerary')) {
            return;
        }

        if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) {
            return;
        }

        if (!current_user_can('edit_post', $post_id)) {
            return;
        }

        if (isset($_POST[self::META_KEY])) {
            $data = wp_unslash($_POST[self::META_KEY]);
            $decoded = json_decode($data, true);

            // Sanitize the data
            if (is_array($decoded)) {
                $sanitized = [];
                foreach ($decoded as $item) {
                    $sanitized[] = [
                        'term_id' => intval($item['term_id'] ?? 0),
                        'name' => sanitize_text_field($item['name'] ?? ''),
                        'time_label' => sanitize_text_field($item['time_label'] ?? ''), // e.g. "Ngày 1"
                        'description' => sanitize_textarea_field($item['description'] ?? ''),
                    ];
                }
                update_post_meta($post_id, self::META_KEY, $sanitized);
            }
        }
    }

    public function enqueueScripts(string $hook): void
    {
        global $post;

        if (($hook === 'post.php' || $hook === 'post-new.php') && $post && $post->post_type === JourneyPostType::POST_TYPE) {
            $extension = \Jankx\Extensions\TourJourney\TourJourneyExtension::get_instance();

            wp_enqueue_style(
                'jankx-journey-builder-css',
                $extension->get_extension_url() . '/assets/builder.css',
                [],
                '1.0.0'
            );

            wp_enqueue_script(
                'jankx-journey-builder-js',
                $extension->get_extension_url() . '/assets/builder.js',
                ['jquery', 'jquery-ui-sortable', 'wp-data', 'wp-api-fetch'],
                '1.0.0',
                true
            );
        }
    }
}
